# Generated by Django 6.0.1 on 2026-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_booking_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=5, verbose_name='Nombre de portes'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5, verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'En attente'), ('Confirmed', 'Confirmé'), ('Active', 'Véhicule en circulation'), ('Completed', 'Véhicule rendu'), ('Cancelled', 'Annulé')], default='Pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manuelle'), ('Automatic', 'Automatique')], max_length=20, verbose_name='Transmission'),
        ),
    ]
