# Generated by Django 6.0.1 on 2026-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_car_doors_car_seats_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Carte Bancaire'), ('Agency', "Paiement à l'agence")], default='Agency', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
